Repository eileenmcnaughton/civicrm_entity, pull requests merged in 2024-04, with the labels that each got.

#438 port to 4.0.x from 436: Include dblocale table names in list of civicrm entity info
  src/SupportedEntities.php
Labels: 4.0.x

#472 fix testLoadContact birthdate assertion
  tests/src/Kernel/CivicrmStorageGetTest.php
Labels: 4.0.x

#461 Update default timezone handling for dates in CiviEntityStorage.php
  src/CiviEntityStorage.php
Labels: 4.0.x

#467 Fix fatal error with caches when updating enabled entities list
  civicrm_entity.admin_form.inc
Labels: 7.x-2.x

#453 Add filter for state province.
  civicrm_entity.libraries.yml
  civicrm_entity.views.inc
  config/schema/civicrm_entity.views.schema.yml
  js/civicrm_entity.states.js
  src/Plugin/views/filter/StateProvince.php
Labels: 4.0.x

#465 Adding a raw value function to return value from values array
  src/Entity/CivicrmEntity.php
Labels: 4.0.x

#430 4.0.x field mappings
  src/CiviEntityStorage.php
Labels: 4.0.x

#474 fix test to use string instead of integer for zip code
  tests/src/FunctionalJavascript/Views/CivicrmAddressViewsTest.php
Labels: 4.0.x

#470 Pathauto
  civicrm_entity.module
Labels: 4.0.x

#449 EntityTag now sends a object.
  civicrm_entity.module
Labels: 8.x-3.x

#423 Adds is Empty/NULL operators
  src/Plugin/views/filter/InOperator.php
Labels: 4.0.x

#476 only check for data in enabled components on module uninstall
  src/CiviEntityStorage.php
Labels: 4.0.x

#475 Bundle info base field definitions fix
  civicrm_entity.module
Labels: 4.0.x

#479 supportedentities update AllCoreTables function
  src/SupportedEntities.php
Labels: 4.0.x

#477 Add pcp.
  src/SupportedEntities.php
Labels: 4.0.x

#478 Adds Checksum validation solution for Drupal Views
  civicrm_entity.services.yml
  src/Access/ContactChecksumCheckAccess.php
  src/Plugin/views/access/ContactChecksum.php
Labels: 4.0.x

#480 deprecation fixes for D11
  civicrm_entity.info.yml
  src/CiviEntityStorage.php
  src/Plugin/views/relationship/CiviCrmContactUser.php
Labels: 4.0.x
